name: Build gh-pages

on:
  push:
    branches:
    - master
    - pages/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Npm install and build
      run: |
        npm install
        npm run refresh
        npm run build
      env:
        CI: true
    - name: Copy files
      run: |
        mkdir ./public
        cp -r ./packages/flaph-vue-example/public ./public/vue
        cp -r ./packages/flaph-react-example/public ./public/react
    - name: Deploy action for GitHub Pages
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      with:
        emptyCommits: false
        keepFiles: false
